# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Flow < Formula
  desc "Real-time network bandwidth monitor for the terminal"
  homepage "https://github.com/programmersd21/flow"
  version "0.2.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/programmersd21/flow/releases/download/v0.2.4/flow_0.2.4_darwin_amd64.tar.gz"
      sha256 "de23934ffe13d898d8bc38417459d7c9664bfd1d4797386fb11e38e30d18a300"

      define_method(:install) do
        bin.install "flow"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/programmersd21/flow/releases/download/v0.2.4/flow_0.2.4_darwin_arm64.tar.gz"
      sha256 "d0e22abca7581ffe7e1bc098b0e7053f0f3ac614ae3837d0af873270549fa679"

      define_method(:install) do
        bin.install "flow"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/programmersd21/flow/releases/download/v0.2.4/flow_0.2.4_linux_amd64.tar.gz"
      sha256 "0bfb7f4adc5658dcece8c3543d2187f3daf84c3d1c70910a027a6d3103e4e256"
      define_method(:install) do
        bin.install "flow"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/programmersd21/flow/releases/download/v0.2.4/flow_0.2.4_linux_arm64.tar.gz"
      sha256 "0b5a25cf664dbcac465723d348948df8d107bd744f584686c19b989c0f1abd7b"
      define_method(:install) do
        bin.install "flow"
      end
    end
  end

  test do
    assert_match "flow", shell_output("#{bin}/flow --version")
  end
end
