# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Flow < Formula
  desc "Real-time network bandwidth monitor for the terminal"
  homepage "https://github.com/programmersd21/flow"
  version "0.3.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/programmersd21/flow/releases/download/v0.3.3/flow_0.3.3_darwin_amd64.tar.gz"
      sha256 "5845d76096dd9c5c6de2daf833b4af9522682a8cc839dfb67e750bffd7739f4a"

      define_method(:install) do
        bin.install "flow"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/programmersd21/flow/releases/download/v0.3.3/flow_0.3.3_darwin_arm64.tar.gz"
      sha256 "8b9b3706b206424c337b3840b5c3439def6c6a9e1a9ee740aa4317765296c669"

      define_method(:install) do
        bin.install "flow"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/programmersd21/flow/releases/download/v0.3.3/flow_0.3.3_linux_amd64.tar.gz"
      sha256 "6a1a3a19737cf794e83f88547657543c239684f924fbe75e38a055e1dfdcd54c"
      define_method(:install) do
        bin.install "flow"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/programmersd21/flow/releases/download/v0.3.3/flow_0.3.3_linux_arm64.tar.gz"
      sha256 "1ccced4e049d924003c3733032b05041995f87f00c9cc81acae7da9346ae43a3"
      define_method(:install) do
        bin.install "flow"
      end
    end
  end

  test do
    assert_match "flow", shell_output("#{bin}/flow --version")
  end
end
